# MAgent AI配置示例
# 复制此文件为 config.toml 并填入你的API密钥

[ai]
# OpenAI配置
openai_api_key = "sk-your-openai-api-key-here"
openai_base_url = "https://api.openai.com/v1"

# Claude (Anthropic)配置
claude_api_key = "sk-ant-your-claude-api-key-here"

# DeepSeek配置
deepseek_api_key = "sk-your-deepseek-api-key-here"

# Gemini配置（可选）
gemini_api_key = "your-gemini-api-key-here"

[models]
# 默认模型配置
default_chat_model = "gpt-3.5-turbo"
default_embedding_model = "text-embedding-3-small"

# Agent专用模型
clarifier_model = "gpt-4o-mini"
innovator_model = "claude-3-haiku-20240307"
critic_model = "gpt-3.5-turbo"
synthesizer_model = "deepseek-chat"
verifier_model = "gpt-4o-mini"
summarizer_model = "gpt-3.5-turbo"

[system]
# 系统配置
max_tokens = 4000
temperature = 0.7
max_iterations = 10
